In [3]:
import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

In [4]:
!pip install -q lettucedetect datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 109.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 9.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.2 which is incompatible.

In [1]:
import numpy as np
import torch

print("NumPy:", np.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

NumPy: 2.5.2
GPU available: True
GPU: Tesla T4

In [2]:
import lettucedetect

print("LettuceDetect installed successfully!")

LettuceDetect installed successfully!

In [3]:
from datasets import load_dataset

dataset = load_dataset("wandb/RAGTruth-processed")

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/1.47k [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 22.3MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 3.88MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/15090 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2700 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'query', 'context', 'output', 'task_type', 'quality', 'model', 'temperature', 'hallucination_labels', 'hallucination_labels_processed', 'input_str'],
        num_rows: 15090
    })
    test: Dataset({
        features: ['id', 'query', 'context', 'output', 'task_type', 'quality', 'model', 'temperature', 'hallucination_labels', 'hallucination_labels_processed', 'input_str'],
        num_rows: 2700
    })
})

In [4]:
print(dataset.keys())

dict_keys(['train', 'test'])

In [5]:
split_name = list(dataset.keys())[0]

print(split_name)
print(dataset[split_name].column_names)

train
['id', 'query', 'context', 'output', 'task_type', 'quality', 'model', 'temperature', 'hallucination_labels', 'hallucination_labels_processed', 'input_str']

In [6]:
example = dataset[split_name][0]

for key, value in example.items():
    print("\n---", key, "---")
    print(value)

--- id ---
0

--- query ---
Summarize the following news within 116 words:

--- context ---
Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank's final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn't bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank's friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it's unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world's most popular books. Read more about Anne Frank's cousin, a keeper of her legacy.

output:

--- output ---
The Anne Frank House has revealed that Anne Frank and her older sister, Margot, likely died at least a month earlier than previously believed. The sisters, who were imprisoned in Nazi concentration camps during the Holocaust, were thought to have died in March 1945, just two weeks before the Bergen-Belsen camp was liberated. However, new research examining archives from the Red Cross, the International Tracing Service, the Bergen-Belsen Memorial, and survivor testimonies suggests that the sisters did not survive until March. The exact dates of their deaths remain unclear, but it is thought that both had symptoms of typhus, the disease they succumbed to, before February 7, 1945.

--- task_type ---
Summary

--- quality ---
good

--- model ---
gpt-4-0613

--- temperature ---
0.699999988079071

--- hallucination_labels ---
[]

--- hallucination_labels_processed ---
{'evident_conflict': 0, 'baseless_info': 0}

--- input_str ---
Below is the original news:
{'question': 'Summarize the following news within 116 words:', 'passages': 'Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank\'s final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn\'t bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank\'s friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it\'s unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world\'s most popular books. Read more about Anne Frank\'s cousin, a keeper of her legacy.\n\noutput:'}
Below is a summary of the news:
The Anne Frank House has revealed that Anne Frank and her older sister, Margot, likely died at least a month earlier than previously believed. The sisters, who were imprisoned in Nazi concentration camps during the Holocaust, were thought to have died in March 1945, just two weeks before the Bergen-Belsen camp was liberated. However, new research examining archives from the Red Cross, the International Tracing Service, the Bergen-Belsen Memorial, and survivor testimonies suggests that the sisters did not survive until March. The exact dates of their deaths remain unclear, but it is thought that both had symptoms of typhus, the disease they succumbed to, before February 7, 1945.
Your task is to identify and label any hallucinated statements in the summary that are unsupported or contradicted by the original news. Then, compile the labeled hallucinated spans into a JSON list, with each list item representing a separate hallucinated span.
Output:

In [7]:
for i in range(5):
    print("\n")
    print("=" * 70)
    print("EXAMPLE:", i)
    print("=" * 70)

    example = dataset[split_name][i]

    for key, value in example.items():
        print(f"\n{key}:")
        print(value)

======================================================================
EXAMPLE: 0
======================================================================

id:
0

query:
Summarize the following news within 116 words:

context:
Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank's final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn't bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank's friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it's unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world's most popular books. Read more about Anne Frank's cousin, a keeper of her legacy.

output:

output:
The Anne Frank House has revealed that Anne Frank and her older sister, Margot, likely died at least a month earlier than previously believed. The sisters, who were imprisoned in Nazi concentration camps during the Holocaust, were thought to have died in March 1945, just two weeks before the Bergen-Belsen camp was liberated. However, new research examining archives from the Red Cross, the International Tracing Service, the Bergen-Belsen Memorial, and survivor testimonies suggests that the sisters did not survive until March. The exact dates of their deaths remain unclear, but it is thought that both had symptoms of typhus, the disease they succumbed to, before February 7, 1945.

task_type:
Summary

quality:
good

model:
gpt-4-0613

temperature:
0.699999988079071

hallucination_labels:
[]

hallucination_labels_processed:
{'evident_conflict': 0, 'baseless_info': 0}

input_str:
Below is the original news:
{'question': 'Summarize the following news within 116 words:', 'passages': 'Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank\'s final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn\'t bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank\'s friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it\'s unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world\'s most popular books. Read more about Anne Frank\'s cousin, a keeper of her legacy.\n\noutput:'}
Below is a summary of the news:
The Anne Frank House has revealed that Anne Frank and her older sister, Margot, likely died at least a month earlier than previously believed. The sisters, who were imprisoned in Nazi concentration camps during the Holocaust, were thought to have died in March 1945, just two weeks before the Bergen-Belsen camp was liberated. However, new research examining archives from the Red Cross, the International Tracing Service, the Bergen-Belsen Memorial, and survivor testimonies suggests that the sisters did not survive until March. The exact dates of their deaths remain unclear, but it is thought that both had symptoms of typhus, the disease they succumbed to, before February 7, 1945.
Your task is to identify and label any hallucinated statements in the summary that are unsupported or contradicted by the original news. Then, compile the labeled hallucinated spans into a JSON list, with each list item representing a separate hallucinated span.
Output:


======================================================================
EXAMPLE: 1
======================================================================

id:
1

query:
Summarize the following news within 116 words:

context:
Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank's final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn't bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank's friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it's unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world's most popular books. Read more about Anne Frank's cousin, a keeper of her legacy.

output:

output:
New research released by the Anne Frank House reveals that Anne Frank and her older sister, Margot, died at least a month earlier than previously believed. The research involved re-examining archives and survivor testimonies, contradicting the previous date of death determined by Dutch authorities. In 1944, the sisters were arrested and sent to Auschwitz-Birkenau, and later separated and sent to the Bergen-Belsen camp. Witnesses described the terrible conditions at the camp, with overcrowding, lack of basic necessities, and a deadly typhus outbreak. The researchers concluded that it is unlikely the sisters survived until March, as witnesses reported symptoms before February 7. The exact dates of their deaths remain unclear. Despite the hardships she faced, Anne Frank's diary continues to be a beloved and influential book.

task_type:
Summary

quality:
good

model:
gpt-3.5-turbo-0613

temperature:
0.699999988079071

hallucination_labels:
[]

hallucination_labels_processed:
{'evident_conflict': 0, 'baseless_info': 0}

input_str:
Below is the original news:
{'question': 'Summarize the following news within 116 words:', 'passages': 'Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank\'s final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn\'t bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank\'s friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it\'s unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world\'s most popular books. Read more about Anne Frank\'s cousin, a keeper of her legacy.\n\noutput:'}
Below is a summary of the news:
New research released by the Anne Frank House reveals that Anne Frank and her older sister, Margot, died at least a month earlier than previously believed. The research involved re-examining archives and survivor testimonies, contradicting the previous date of death determined by Dutch authorities. In 1944, the sisters were arrested and sent to Auschwitz-Birkenau, and later separated and sent to the Bergen-Belsen camp. Witnesses described the terrible conditions at the camp, with overcrowding, lack of basic necessities, and a deadly typhus outbreak. The researchers concluded that it is unlikely the sisters survived until March, as witnesses reported symptoms before February 7. The exact dates of their deaths remain unclear. Despite the hardships she faced, Anne Frank's diary continues to be a beloved and influential book.
Your task is to identify and label any hallucinated statements in the summary that are unsupported or contradicted by the original news. Then, compile the labeled hallucinated spans into a JSON list, with each list item representing a separate hallucinated span.
Output:


======================================================================
EXAMPLE: 2
======================================================================

id:
2

query:
Summarize the following news within 116 words:

context:
Seventy years ago, Anne Frank died of typhus in a Nazi concentration camp at the age of 15. Just two weeks after her supposed death on March 31, 1945, the Bergen-Belsen concentration camp where she had been imprisoned was liberated -- timing that showed how close the Jewish diarist had been to surviving the Holocaust. But new research released by the Anne Frank House shows that Anne and her older sister, Margot Frank, died at least a month earlier than previously thought. Researchers re-examined archives of the Red Cross, the International Training Service and the Bergen-Belsen Memorial, along with testimonies of survivors. They concluded that Anne and Margot probably did not survive to March 1945 -- contradicting the date of death which had previously been determined by Dutch authorities. In 1944, Anne and seven others hiding in the Amsterdam secret annex were arrested and sent to the  Auschwitz-Birkenau concentration camp. Anne Frank's final entry. That same year, Anne and Margot were separated from their mother and sent away to work as slave labor at the Bergen-Belsen camp in Germany. Days at the camp were filled with terror and dread, witnesses said. The sisters stayed in a section of the overcrowded camp with no lighting, little water and no latrine. They slept on lice-ridden straw and violent storms shredded the tents, according to the researchers. Like the other prisoners, the sisters endured long hours at roll call. Her classmate, Nannette Blitz, recalled seeing Anne there in December 1944: "She was no more than a skeleton by then. She was wrapped in a blanket; she couldn't bear to wear her clothes anymore because they were crawling with lice." Listen to Anne Frank's friends describe her concentration camp experience. As the Russians advanced further, the Bergen-Belsen concentration camp became even more crowded, bringing more disease. A deadly typhus outbreak caused thousands to die each day. Typhus is an infectious disease caused by lice that breaks out in places with poor hygiene. The disease causes high fever, chills and skin eruptions. "Because of the lice infesting the bedstraw and her clothes, Anne was exposed to the main carrier of epidemic typhus for an extended period," museum researchers wrote. They concluded that it's unlikely the sisters survived until March, because witnesses at the camp said the sisters both had symptoms before February 7. "Most deaths caused by typhus occur around twelve days after the first symptoms appear," wrote  authors Erika Prins and Gertjan Broek. The exact dates of death for Anne and Margot remain unclear. Margot died before Anne. "Anne never gave up hope," said Blitz, her friend. "She was absolutely convinced she would survive." Her diary endures as one of the world's most popular books. Read more about Anne Frank's cousin, a keeper of her legacy.

output:

output:

In [8]:
from lettucedetect.models.inference import HallucinationDetector

detector = HallucinationDetector(
    method="transformer",
    model_path="KRLabsOrg/lettucedect-v2-mmbert-base"
)

print("LettuceDetect loaded!")

config.json:   0%|          | 0.00/2.07k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/46.4k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 34.4MB

tokenizer.json: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.23GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

LettuceDetect loaded!

In [9]:
context = [
    "The Eiffel Tower is located in Paris. It was completed in 1889."
]

question = "Tell me about the Eiffel Tower."

answer = (
    "The Eiffel Tower is located in Paris. "
    "It was completed in 1889. "
    "It is 900 meters tall and was designed by Leonardo da Vinci."
)

predictions = detector.predict(
    context=context,
    question=question,
    answer=answer,
    output_format="spans"
)

print(predictions)

[{'start': 70, 'end': 85, 'confidence': 0.6680112481117249, 'text': '900 meters tall'}, {'start': 89, 'end': 102, 'confidence': 0.5113643407821655, 'text': ' was designed'}, {'start': 105, 'end': 123, 'confidence': 0.5982829332351685, 'text': ' Leonardo da Vinci'}]

In [10]:
example = dataset["train"][0]

context = [example["context"]]
question = example["query"]
answer = example["output"]

predictions = detector.predict(
    context=context,
    question=question,
    answer=answer,
    output_format="spans"
)

print("========== RAGTRUTH ==========")
print(example["hallucination_labels"])

print("\n========== LETTUCEDETECT ==========")
print(predictions)

========== RAGTRUTH ==========
[]

========== LETTUCEDETECT ==========
[]

In [11]:
example = dataset["train"][2]

context = [example["context"]]
question = example["query"]
answer = example["output"]

predictions = detector.predict(
    context=context,
    question=question,
    answer=answer,
    output_format="spans"
)

print("========== RAGTRUTH ==========")
print(example["hallucination_labels"])

print("\n========== RAGTRUTH PROCESSED ==========")
print(example["hallucination_labels_processed"])

print("\n========== LETTUCEDETECT ==========")

if len(predictions) == 0:
    print("No hallucination detected")
else:
    for pred in predictions:
        print("Detected:", pred["text"])
        print("Confidence:", round(pred["confidence"], 3))
        print()

========== RAGTRUTH ==========
[{"start": 636, "end": 653, "text": "February 7, 2022.", "meta": "EVIDENT CONFLICT\nOriginal: February 7 (1945)\nGenerated: February 7, 2022", "label_type": "Evident Conflict", "implicit_true": false, "due_to_null": false}, {"start": 871, "end": 969, "text": "has prompted the Anne Frank House to issue a corrected statement regarding the date of her passing", "meta": "HIGH INTRODUCTION OF NEW INFORMATION\nIt was not mentioned in the source content that the Anne Frank House issue a corrected statement regarding the date of her passing.", "label_type": "Evident Baseless Info", "implicit_true": false, "due_to_null": false}, {"start": 607, "end": 646, "text": "believed to have died before February 7", "meta": "EVIDENT CONFLICT\nOriginal:  exact dates of death for Anne and Margot remain unclear; sisters both had symptoms before February 7\nGenerated: believed to have died before February 7", "label_type": "Evident Conflict", "implicit_true": false, "due_to_null": false}]

========== RAGTRUTH PROCESSED ==========
{'evident_conflict': 1, 'baseless_info': 1}

========== LETTUCEDETECT ==========
Detected:  before February 7, 2022
Confidence: 0.861

In [12]:
from typing import List, Dict, Tuple


def span_overlap(pred_span: Tuple[int, int], gold_span: Tuple[int, int]) -> float:
    """
    Calculate overlap (IoU) between predicted and actual hallucination spans.
    """
    p_start, p_end = pred_span
    g_start, g_end = gold_span

    inter_start = max(p_start, g_start)
    inter_end = min(p_end, g_end)

    intersection = max(0, inter_end - inter_start)

    union = max(p_end, g_end) - min(p_start, g_start)

    if union == 0:
        return 0.0

    return intersection / union


def match_spans(predictions, gold_spans, overlap_threshold=0.3):
    """
    Match LettuceDetect predictions with RAGTruth hallucination spans.
    """

    matched = []
    used_gold_idx = set()
    unmatched_preds = []

    for pred in predictions:

        pred_range = (pred["start"], pred["end"])

        best_score = 0.0
        best_gold_idx = None

        for i, gold in enumerate(gold_spans):

            if i in used_gold_idx:
                continue

            gold_range = (gold["start"], gold["end"])

            score = span_overlap(pred_range, gold_range)

            if score > best_score:
                best_score = score
                best_gold_idx = i

        if best_score >= overlap_threshold and best_gold_idx is not None:

            matched.append(
                (pred, gold_spans[best_gold_idx], best_score)
            )

            used_gold_idx.add(best_gold_idx)

        else:
            unmatched_preds.append(pred)

    unmatched_golds = [
        g for i, g in enumerate(gold_spans)
        if i not in used_gold_idx
    ]

    return matched, unmatched_preds, unmatched_golds


def evaluate_dataset(all_predictions, all_gold_spans, overlap_threshold=0.3):

    total_tp = 0
    total_fp = 0
    total_fn = 0

    for preds, golds in zip(all_predictions, all_gold_spans):

        matched, unmatched_preds, unmatched_golds = match_spans(
            preds,
            golds,
            overlap_threshold
        )

        total_tp += len(matched)
        total_fp += len(unmatched_preds)
        total_fn += len(unmatched_golds)

    precision = (
        total_tp / (total_tp + total_fp)
        if (total_tp + total_fp) > 0
        else 0
    )

    recall = (
        total_tp / (total_tp + total_fn)
        if (total_tp + total_fn) > 0
        else 0
    )

    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0
    )

    return {
        "precision": round(precision, 3),
        "recall": round(recall, 3),
        "f1": round(f1, 3),
        "total_tp": total_tp,
        "total_fp": total_fp,
        "total_fn": total_fn
    }


print("Evaluation functions loaded successfully!")

Evaluation functions loaded successfully!

In [13]:
import ast

example = dataset["train"][2]

context = [example["context"]]
question = example["query"]
answer = example["output"]

# Run LettuceDetect
predictions = detector.predict(
    context=context,
    question=question,
    answer=answer,
    output_format="spans"
)

# RAGTruth stores hallucination_labels as a STRING
gold_spans_raw = example["hallucination_labels"]

# Convert string -> actual Python list of dictionaries
import json

gold_spans = json.loads(gold_spans_raw)

print("Predictions:")
print(predictions)

print("\nGold spans:")
print(gold_spans)

print("\nGold type:", type(gold_spans))

# Evaluate
results = evaluate_dataset(
    [predictions],
    [gold_spans],
    overlap_threshold=0.3
)

print("\n========== TEST EVALUATION ==========")
print("Precision:", results["precision"])
print("Recall:   ", results["recall"])
print("F1 Score: ", results["f1"])

print()
print("TP:", results["total_tp"])
print("FP:", results["total_fp"])
print("FN:", results["total_fn"])

Predictions:
[{'start': 628, 'end': 652, 'confidence': 0.8607193827629089, 'text': ' before February 7, 2022'}]

Gold spans:
[{'start': 636, 'end': 653, 'text': 'February 7, 2022.', 'meta': 'EVIDENT CONFLICT\nOriginal: February 7 (1945)\nGenerated: February 7, 2022', 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}, {'start': 871, 'end': 969, 'text': 'has prompted the Anne Frank House to issue a corrected statement regarding the date of her passing', 'meta': 'HIGH INTRODUCTION OF NEW INFORMATION\nIt was not mentioned in the source content that the Anne Frank House issue a corrected statement regarding the date of her passing.', 'label_type': 'Evident Baseless Info', 'implicit_true': False, 'due_to_null': False}, {'start': 607, 'end': 646, 'text': 'believed to have died before February 7', 'meta': 'EVIDENT CONFLICT\nOriginal:  exact dates of death for Anne and Margot remain unclear; sisters both had symptoms before February 7\nGenerated: believed to have died before February 7', 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}]

Gold type: <class 'list'>

========== TEST EVALUATION ==========
Precision: 1.0
Recall:    0.333
F1 Score:  0.5

TP: 1
FP: 0
FN: 2

In [14]:
example = dataset["train"][2]

print("GOLD SPANS:")
print(example["hallucination_labels"])

print("\nTYPE:")
print(type(example["hallucination_labels"]))

print("\nFIRST ITEM:")
print(example["hallucination_labels"][0])

print("\nFIRST ITEM TYPE:")
print(type(example["hallucination_labels"][0]))

GOLD SPANS:
[{"start": 636, "end": 653, "text": "February 7, 2022.", "meta": "EVIDENT CONFLICT\nOriginal: February 7 (1945)\nGenerated: February 7, 2022", "label_type": "Evident Conflict", "implicit_true": false, "due_to_null": false}, {"start": 871, "end": 969, "text": "has prompted the Anne Frank House to issue a corrected statement regarding the date of her passing", "meta": "HIGH INTRODUCTION OF NEW INFORMATION\nIt was not mentioned in the source content that the Anne Frank House issue a corrected statement regarding the date of her passing.", "label_type": "Evident Baseless Info", "implicit_true": false, "due_to_null": false}, {"start": 607, "end": 646, "text": "believed to have died before February 7", "meta": "EVIDENT CONFLICT\nOriginal:  exact dates of death for Anne and Margot remain unclear; sisters both had symptoms before February 7\nGenerated: believed to have died before February 7", "label_type": "Evident Conflict", "implicit_true": false, "due_to_null": false}]

TYPE:
<class 'str'>

FIRST ITEM:
[

FIRST ITEM TYPE:
<class 'str'>

In [15]:
print("PREDICTIONS:")
print(predictions)

print("\nPREDICTIONS TYPE:")
print(type(predictions))

if len(predictions) > 0:
    print("\nFIRST PREDICTION:")
    print(predictions[0])
    print(type(predictions[0]))

PREDICTIONS:
[{'start': 628, 'end': 652, 'confidence': 0.8607193827629089, 'text': ' before February 7, 2022'}]

PREDICTIONS TYPE:
<class 'list'>

FIRST PREDICTION:
{'start': 628, 'end': 652, 'confidence': 0.8607193827629089, 'text': ' before February 7, 2022'}
<class 'dict'>

In [16]:
import json

all_predictions = []
all_gold_spans = []

NUM_EXAMPLES = len(dataset["test"])

for i in range(NUM_EXAMPLES):

    example = dataset["test"][i]

    context = [example["context"]]
    question = example["query"]
    answer = example["output"]

    # LettuceDetect prediction
    predictions = detector.predict(
        context=context,
        question=question,
        answer=answer,
        output_format="spans"
    )

    # RAGTruth gold labels
    gold_spans_raw = example["hallucination_labels"]

    # Convert JSON string -> Python list
    gold_spans = json.loads(gold_spans_raw)

    all_predictions.append(predictions)
    all_gold_spans.append(gold_spans)

    print(f"Completed {i + 1}/{NUM_EXAMPLES}")

print("\nAll examples completed!")

Completed 1/2700
Completed 2/2700
Completed 3/2700
Completed 4/2700
Completed 5/2700
Completed 6/2700
Completed 7/2700
Completed 8/2700
Completed 9/2700
Completed 10/2700
Completed 11/2700
Completed 12/2700
Completed 13/2700
Completed 14/2700
Completed 15/2700
Completed 16/2700
Completed 17/2700
Completed 18/2700
Completed 19/2700
Completed 20/2700
Completed 21/2700
Completed 22/2700
Completed 23/2700
Completed 24/2700
Completed 25/2700
Completed 26/2700
Completed 27/2700
Completed 28/2700
Completed 29/2700
Completed 30/2700
Completed 31/2700
Completed 32/2700
Completed 33/2700
Completed 34/2700
Completed 35/2700
Completed 36/2700
Completed 37/2700
Completed 38/2700
Completed 39/2700
Completed 40/2700
Completed 41/2700
Completed 42/2700
Completed 43/2700
Completed 44/2700
Completed 45/2700
Completed 46/2700
Completed 47/2700
Completed 48/2700
Completed 49/2700
Completed 50/2700
Completed 51/2700
Completed 52/2700
Completed 53/2700
Completed 54/2700
Completed 55/2700
Completed 56/2700
Completed 57/2700
Completed 58/2700
Completed 59/2700
Completed 60/2700
Completed 61/2700
Completed 62/2700
Completed 63/2700
Completed 64/2700
Completed 65/2700
Completed 66/2700
Completed 67/2700
Completed 68/2700
Completed 69/2700
Completed 70/2700
Completed 71/2700
Completed 72/2700
Completed 73/2700
Completed 74/2700
Completed 75/2700
Completed 76/2700
Completed 77/2700
Completed 78/2700
Completed 79/2700
Completed 80/2700
Completed 81/2700
Completed 82/2700
Completed 83/2700
Completed 84/2700
Completed 85/2700
Completed 86/2700
Completed 87/2700
Completed 88/2700
Completed 89/2700
Completed 90/2700
Completed 91/2700
Completed 92/2700
Completed 93/2700
Completed 94/2700
Completed 95/2700
Completed 96/2700
Completed 97/2700
Completed 98/2700
Completed 99/2700
Completed 100/2700
Completed 101/2700
Completed 102/2700
Completed 103/2700
Completed 104/2700
Completed 105/2700
Completed 106/2700
Completed 107/2700
Completed 108/2700
Completed 109/2700
Completed 110/2700
Completed 111/2700
Completed 112/2700
Completed 113/2700
Completed 114/2700
Completed 115/2700
Completed 116/2700
Completed 117/2700
Completed 118/2700
Completed 119/2700
Completed 120/2700
Completed 121/2700
Completed 122/2700
Completed 123/2700
Completed 124/2700
Completed 125/2700
Completed 126/2700
Completed 127/2700
Completed 128/2700
Completed 129/2700
Completed 130/2700
Completed 131/2700
Completed 132/2700
Completed 133/2700
Completed 134/2700
Completed 135/2700
Completed 136/2700
Completed 137/2700
Completed 138/2700
Completed 139/2700
Completed 140/2700
Completed 141/2700
Completed 142/2700
Completed 143/2700
Completed 144/2700
Completed 145/2700
Completed 146/2700
Completed 147/2700
Completed 148/2700
Completed 149/2700
Completed 150/2700
Completed 151/2700
Completed 152/2700
Completed 153/2700
Completed 154/2700
Completed 155/2700
Completed 156/2700
Completed 157/2700
Completed 158/2700
Completed 159/2700
Completed 160/2700
Completed 161/2700
Completed 162/2700
Completed 163/2700
Completed 164/2700
Completed 165/2700
Completed 166/2700
Completed 167/2700
Completed 168/2700
Completed 169/2700
Completed 170/2700
Completed 171/2700
Completed 172/2700
Completed 173/2700
Completed 174/2700
Completed 175/2700
Completed 176/2700
Completed 177/2700
Completed 178/2700
Completed 179/2700
Completed 180/2700
Completed 181/2700
Completed 182/2700
Completed 183/2700
Completed 184/2700
Completed 185/2700
Completed 186/2700
Completed 187/2700
Completed 188/2700
Completed 189/2700
Completed 190/2700
Completed 191/2700
Completed 192/2700
Completed 193/2700
Completed 194/2700
Completed 195/2700
Completed 196/2700
Completed 197/2700
Completed 198/2700
Completed 199/2700
Completed 200/2700
Completed 201/2700
Completed 202/2700
Completed 203/2700
Completed 204/2700
Completed 205/2700
Completed 206/2700
Completed 207/2700
Completed 208/2700
Completed 209/2700
Completed 210/2700
Completed 211/2700
Completed 212/2700
Completed 213/2700
Completed 214/2700
Completed 215/2700
Completed 216/2700
Completed 217/2700
Completed 218/2700
Completed 219/2700
Completed 220/2700
Completed 221/2700
Completed 222/2700
Completed 223/2700
Completed 224/2700
Completed 225/2700
Completed 226/2700
Completed 227/2700
Completed 228/2700
Completed 229/2700
Completed 230/2700
Completed 231/2700
Completed 232/2700
Completed 233/2700
Completed 234/2700
Completed 235/2700
Completed 236/2700
Completed 237/2700
Completed 238/2700
Completed 239/2700
Completed 240/2700
Completed 241/2700
Completed 242/2700
Completed 243/2700
Completed 244/2700
Completed 245/2700
Completed 246/2700
Completed 247/2700
Completed 248/2700
Completed 249/2700
Completed 250/2700
Completed 251/2700
Completed 252/2700
Completed 253/2700
Completed 254/2700
Completed 255/2700
Completed 256/2700
Completed 257/2700
Completed 258/2700
Completed 259/2700
Completed 260/2700
Completed 261/2700
Completed 262/2700
Completed 263/2700
Completed 264/2700
Completed 265/2700
Completed 266/2700
Completed 267/2700
Completed 268/2700
Completed 269/2700
Completed 270/2700
Completed 271/2700
Completed 272/2700
Completed 273/2700
Completed 274/2700
Completed 275/2700
Completed 276/2700
Completed 277/2700
Completed 278/2700
Completed 279/2700
Completed 280/2700
Completed 281/2700
Completed 282/2700
Completed 283/2700
Completed 284/2700
Completed 285/2700
Completed 286/2700
Completed 287/2700
Completed 288/2700
Completed 289/2700
Completed 290/2700
Completed 291/2700
Completed 292/2700
Completed 293/2700
Completed 294/2700
Completed 295/2700
Completed 296/2700
Completed 297/2700
Completed 298/2700
Completed 299/2700
Completed 300/2700
Completed 301/2700
Completed 302/2700
Completed 303/2700
Completed 304/2700
Completed 305/2700
Completed 306/2700
Completed 307/2700
Completed 308/2700
Completed 309/2700
Completed 310/2700
Completed 311/2700
Completed 312/2700
Completed 313/2700
Completed 314/2700
Completed 315/2700
Completed 316/2700
Completed 317/2700
Completed 318/2700
Completed 319/2700
Completed 320/2700
Completed 321/2700
Completed 322/2700
Completed 323/2700
Completed 324/2700
Completed 325/2700
Completed 326/2700
Completed 327/2700
Completed 328/2700
Completed 329/2700
Completed 330/2700
Completed 331/2700
Completed 332/2700
Completed 333/2700
Completed 334/2700
Completed 335/2700
Completed 336/2700
Completed 337/2700
Completed 338/2700
Completed 339/2700
Completed 340/2700
Completed 341/2700
Completed 342/2700
Completed 343/2700
Completed 344/2700
Completed 345/2700
Completed 346/2700
Completed 347/2700
Completed 348/2700
Completed 349/2700
Completed 350/2700
Completed 351/2700
Completed 352/2700
Completed 353/2700
Completed 354/2700
Completed 355/2700
Completed 356/2700
Completed 357/2700
Completed 358/2700
Completed 359/2700
Completed 360/2700
Completed 361/2700
Completed 362/2700
Completed 363/2700
Completed 364/2700
Completed 365/2700
Completed 366/2700
Completed 367/2700
Completed 368/2700
Completed 369/2700
Completed 370/2700
Completed 371/2700
Completed 372/2700
Completed 373/2700
Completed 374/2700
Completed 375/2700
Completed 376/2700
Completed 377/2700
Completed 378/2700
Completed 379/2700
Completed 380/2700
Completed 381/2700
Completed 382/2700
Completed 383/2700
Completed 384/2700
Completed 385/2700
Completed 386/2700
Completed 387/2700
Completed 388/2700
Completed 389/2700
Completed 390/2700
Completed 391/2700
Completed 392/2700
Completed 393/2700
Completed 394/2700
Completed 395/2700
Completed 396/2700
Completed 397/2700
Completed 398/2700
Completed 399/2700
Completed 400/2700
Completed 401/2700
Completed 402/2700
Completed 403/2700
Completed 404/2700
Completed 405/2700
Completed 406/2700
Completed 407/2700
Completed 408/2700
Completed 409/2700
Completed 410/2700
Completed 411/2700
Completed 412/2700
Completed 413/2700
Completed 414/2700
Completed 415/2700
Completed 416/2700
Completed 417/2700
Completed 418/2700
Completed 419/2700
Completed 420/2700
Completed 421/2700
Completed 422/2700
Completed 423/2700
Completed 424/2700
Completed 425/2700
Completed 426/2700
Completed 427/2700
Completed 428/2700
Completed 429/2700
Completed 430/2700
Completed 431/2700
Completed 432/2700
Completed 433/2700
Completed 434/2700
Completed 435/2700
Completed 436/2700
Completed 437/2700
Completed 438/2700
Completed 439/2700
Completed 440/2700
Completed 441/2700
Completed 442/2700
Completed 443/2700
Completed 444/2700
Completed 445/2700
Completed 446/2700
Completed 447/2700
Completed 448/2700
Completed 449/2700
Completed 450/2700
Completed 451/2700
Completed 452/2700
Completed 453/2700
Completed 454/2700
Completed 455/2700
Completed 456/2700
Completed 457/2700
Completed 458/2700
Completed 459/2700
Completed 460/2700
Completed 461/2700
Completed 462/2700
Completed 463/2700
Completed 464/2700
Completed 465/2700
Completed 466/2700
Completed 467/2700
Completed 468/2700
Completed 469/2700
Completed 470/2700
Completed 471/2700
Completed 472/2700
Completed 473/2700
Completed 474/2700
Completed 475/2700
Completed 476/2700
Completed 477/2700
Completed 478/2700
Completed 479/2700
Completed 480/2700
Completed 481/2700
Completed 482/2700
Completed 483/2700
Completed 484/2700
Completed 485/2700
Completed 486/2700
Completed 487/2700
Completed 488/2700
Completed 489/2700
Completed 490/2700
Completed 491/2700
Completed 492/2700
Completed 493/2700
Completed 494/2700
Completed 495/2700
Completed 496/2700
Completed 497/2700
Completed 498/2700
Completed 499/2700
Completed 500/2700
Completed 501/2700
Completed 502/2700
Completed 503/2700
Completed 504/2700
Completed 505/2700
Completed 506/2700
Completed 507/2700
Completed 508/2700
Completed 509/2700
Completed 510/2700
Completed 511/2700
Completed 512/2700
Completed 513/2700
Completed 514/2700
Completed 515/2700
Completed 516/2700
Completed 517/2700
Completed 518/2700
Completed 519/2700
Completed 520/2700
Completed 521/2700
Completed 522/2700
Completed 523/2700
Completed 524/2700
Completed 525/2700
Completed 526/2700
Completed 527/2700
Completed 528/2700
Completed 529/2700
Completed 530/2700
Completed 531/2700
Completed 532/2700
Completed 533/2700
Completed 534/2700
Completed 535/2700
Completed 536/2700
Completed 537/2700
Completed 538/2700
Completed 539/2700
Completed 540/2700
Completed 541/2700
Completed 542/2700
Completed 543/2700
Completed 544/2700
Completed 545/2700
Completed 546/2700
Completed 547/2700
Completed 548/2700
Completed 549/2700
Completed 550/2700
Completed 551/2700
Completed 552/2700
Completed 553/2700
Completed 554/2700
Completed 555/2700
Completed 556/2700
Completed 557/2700
Completed 558/2700
Completed 559/2700
Completed 560/2700
Completed 561/2700
Completed 562/2700
Completed 563/2700
Completed 564/2700
Completed 565/2700
Completed 566/2700
Completed 567/2700
Completed 568/2700
Completed 569/2700
Completed 570/2700
Completed 571/2700
Completed 572/2700
Completed 573/2700
Completed 574/2700
Completed 575/2700
Completed 576/2700
Completed 577/2700
Completed 578/2700
Completed 579/2700
Completed 580/2700
Completed 581/2700
Completed 582/2700
Completed 583/2700
Completed 584/2700
Completed 585/2700
Completed 586/2700
Completed 587/2700
Completed 588/2700
Completed 589/2700
Completed 590/2700
Completed 591/2700
Completed 592/2700
Completed 593/2700
Completed 594/2700
Completed 595/2700
Completed 596/2700
Completed 597/2700
Completed 598/2700
Completed 599/2700
Completed 600/2700
Completed 601/2700
Completed 602/2700
Completed 603/2700
Completed 604/2700
Completed 605/2700
Completed 606/2700
Completed 607/2700
Completed 608/2700
Completed 609/2700
Completed 610/2700
Completed 611/2700
Completed 612/2700
Completed 613/2700
Completed 614/2700
Completed 615/2700
Completed 616/2700
Completed 617/2700
Completed 618/2700
Completed 619/2700
Completed 620/2700
Completed 621/2700
Completed 622/2700
Completed 623/2700
Completed 624/2700
Completed 625/2700
Completed 626/2700
Completed 627/2700
Completed 628/2700
Completed 629/2700
Completed 630/2700
Completed 631/2700
Completed 632/2700
Completed 633/2700
Completed 634/2700
Completed 635/2700
Completed 636/2700
Completed 637/2700
Completed 638/2700
Completed 639/2700
Completed 640/2700
Completed 641/2700
Completed 642/2700
Completed 643/2700
Completed 644/2700
Completed 645/2700
Completed 646/2700
Completed 647/2700
Completed 648/2700
Completed 649/2700
Completed 650/2700
Completed 651/2700
Completed 652/2700
Completed 653/2700
Completed 654/2700
Completed 655/2700
Completed 656/2700
Completed 657/2700
Completed 658/2700
Completed 659/2700
Completed 660/2700
Completed 661/2700
Completed 662/2700
Completed 663/2700
Completed 664/2700
Completed 665/2700
Completed 666/2700
Completed 667/2700
Completed 668/2700
Completed 669/2700
Completed 670/2700
Completed 671/2700
Completed 672/2700
Completed 673/2700
Completed 674/2700
Completed 675/2700
Completed 676/2700
Completed 677/2700
Completed 678/2700
Completed 679/2700
Completed 680/2700
Completed 681/2700
Completed 682/2700
Completed 683/2700
Completed 684/2700
Completed 685/2700
Completed 686/2700
Completed 687/2700
Completed 688/2700
Completed 689/2700
Completed 690/2700
Completed 691/2700
Completed 692/2700
Completed 693/2700
Completed 694/2700
Completed 695/2700
Completed 696/2700
Completed 697/2700
Completed 698/2700
Completed 699/2700
Completed 700/2700
Completed 701/2700
Completed 702/2700
Completed 703/2700
Completed 704/2700
Completed 705/2700
Completed 706/2700
Completed 707/2700
Completed 708/2700
Completed 709/2700
Completed 710/2700
Completed 711/2700
Completed 712/2700
Completed 713/2700
Completed 714/2700
Completed 715/2700
Completed 716/2700
Completed 717/2700
Completed 718/2700
Completed 719/2700
Completed 720/2700
Completed 721/2700
Completed 722/2700
Completed 723/2700
Completed 724/2700
Completed 725/2700
Completed 726/2700
Completed 727/2700
Completed 728/2700
Completed 729/2700
Completed 730/2700
Completed 731/2700
Completed 732/2700
Completed 733/2700
Completed 734/2700
Completed 735/2700
Completed 736/2700
Completed 737/2700
Completed 738/2700
Completed 739/2700
Completed 740/2700
Completed 741/2700
Completed 742/2700
Completed 743/2700
Completed 744/2700
Completed 745/2700
Completed 746/2700
Completed 747/2700
Completed 748/2700
Completed 749/2700
Completed 750/2700
Completed 751/2700
Completed 752/2700
Completed 753/2700
Completed 754/2700
Completed 755/2700
Completed 756/2700
Completed 757/2700
Completed 758/2700
Completed 759/2700
Completed 760/2700
Completed 761/2700
Completed 762/2700
Completed 763/2700
Completed 764/2700
Completed 765/2700
Completed 766/2700
Completed 767/2700
Completed 768/2700
Completed 769/2700
Completed 770/2700
Completed 771/2700
Completed 772/2700
Completed 773/2700
Completed 774/2700
Completed 775/2700
Completed 776/2700
Completed 777/2700
Completed 778/2700
Completed 779/2700
Completed 780/2700
Completed 781/2700
Completed 782/2700
Completed 783/2700
Completed 784/2700
Completed 785/2700
Completed 786/2700
Completed 787/2700
Completed 788/2700
Completed 789/2700
Completed 790/2700
Completed 791/2700
Completed 792/2700
Completed 793/2700
Completed 794/2700
Completed 795/2700
Completed 796/2700
Completed 797/2700
Completed 798/2700
Completed 799/2700
Completed 800/2700
Completed 801/2700
Completed 802/2700
Completed 803/2700
Completed 804/2700
Completed 805/2700
Completed 806/2700
Completed 807/2700
Completed 808/2700
Completed 809/2700
Completed 810/2700
Completed 811/2700
Completed 812/2700
Completed 813/2700
Completed 814/2700
Completed 815/2700
Completed 816/2700
Completed 817/2700
Completed 818/2700
Completed 819/2700
Completed 820/2700
Completed 821/2700
Completed 822/2700
Completed 823/2700
Completed 824/2700
Completed 825/2700
Completed 826/2700
Completed 827/2700
Completed 828/2700
Completed 829/2700
Completed 830/2700
Completed 831/2700
Completed 832/2700
Completed 833/2700
Completed 834/2700
Completed 835/2700
Completed 836/2700
Completed 837/2700
Completed 838/2700
Completed 839/2700
Completed 840/2700
Completed 841/2700
Completed 842/2700
Completed 843/2700
Completed 844/2700
Completed 845/2700
Completed 846/2700
Completed 847/2700
Completed 848/2700
Completed 849/2700
Completed 850/2700
Completed 851/2700
Completed 852/2700
Completed 853/2700
Completed 854/2700
Completed 855/2700
Completed 856/2700
Completed 857/2700
Completed 858/2700
Completed 859/2700
Completed 860/2700
Completed 861/2700
Completed 862/2700
Completed 863/2700
Completed 864/2700
Completed 865/2700
Completed 866/2700
Completed 867/2700
Completed 868/2700
Completed 869/2700
Completed 870/2700
Completed 871/2700
Completed 872/2700
Completed 873/2700
Completed 874/2700
Completed 875/2700
Completed 876/2700
Completed 877/2700
Completed 878/2700
Completed 879/2700
Completed 880/2700
Completed 881/2700
Completed 882/2700
Completed 883/2700
Completed 884/2700
Completed 885/2700
Completed 886/2700
Completed 887/2700
Completed 888/2700
Completed 889/2700
Completed 890/2700
Completed 891/2700
Completed 892/2700
Completed 893/2700
Completed 894/2700
Completed 895/2700
Completed 896/2700
Completed 897/2700
Completed 898/2700
Completed 899/2700
Completed 900/2700
Completed 901/2700
Completed 902/2700
Completed 903/2700
Completed 904/2700
Completed 905/2700
Completed 906/2700
Completed 907/2700
Completed 908/2700
Completed 909/2700
Completed 910/2700
Completed 911/2700
Completed 912/2700
Completed 913/2700
Completed 914/2700
Completed 915/2700
Completed 916/2700
Completed 917/2700
Completed 918/2700
Completed 919/2700
Completed 920/2700
Completed 921/2700
Completed 922/2700
Completed 923/2700
Completed 924/2700
Completed 925/2700
Completed 926/2700
Completed 927/2700
Completed 928/2700
Completed 929/2700
Completed 930/2700
Completed 931/2700
Completed 932/2700
Completed 933/2700
Completed 934/2700
Completed 935/2700
Completed 936/2700
Completed 937/2700
Completed 938/2700
Completed 939/2700
Completed 940/2700
Completed 941/2700
Completed 942/2700
Completed 943/2700
Completed 944/2700
Completed 945/2700
Completed 946/2700
Completed 947/2700
Completed 948/2700
Completed 949/2700
Completed 950/2700
Completed 951/2700
Completed 952/2700
Completed 953/2700
Completed 954/2700
Completed 955/2700
Completed 956/2700
Completed 957/2700
Completed 958/2700
Completed 959/2700
Completed 960/2700
Completed 961/2700
Completed 962/2700
Completed 963/2700
Completed 964/2700
Completed 965/2700
Completed 966/2700
Completed 967/2700
Completed 968/2700
Completed 969/2700
Completed 970/2700
Completed 971/2700
Completed 972/2700
Completed 973/2700
Completed 974/2700
Completed 975/2700
Completed 976/2700
Completed 977/2700
Completed 978/2700
Completed 979/2700
Completed 980/2700
Completed 981/2700
Completed 982/2700
Completed 983/2700
Completed 984/2700
Completed 985/2700
Completed 986/2700
Completed 987/2700
Completed 988/2700
Completed 989/2700
Completed 990/2700
Completed 991/2700
Completed 992/2700
Completed 993/2700
Completed 994/2700
Completed 995/2700
Completed 996/2700
Completed 997/2700
Completed 998/2700
Completed 999/2700
Completed 1000/2700
Completed 1001/2700
Completed 1002/2700
Completed 1003/2700
Completed 1004/2700
Completed 1005/2700
Completed 1006/2700
Completed 1007/2700
Completed 1008/2700
Completed 1009/2700
Completed 1010/2700
Completed 1011/2700
Completed 1012/2700
Completed 1013/2700
Completed 1014/2700
Completed 1015/2700
Completed 1016/2700
Completed 1017/2700
Completed 1018/2700
Completed 1019/2700
Completed 1020/2700
Completed 1021/2700
Completed 1022/2700
Completed 1023/2700
Completed 1024/2700
Completed 1025/2700
Completed 1026/2700
Completed 1027/2700
Completed 1028/2700
Completed 1029/2700
Completed 1030/2700
Completed 1031/2700
Completed 1032/2700
Completed 1033/2700
Completed 1034/2700
Completed 1035/2700
Completed 1036/2700
Completed 1037/2700
Completed 1038/2700
Completed 1039/2700
Completed 1040/2700
Completed 1041/2700
Completed 1042/2700
Completed 1043/2700
Completed 1044/2700
Completed 1045/2700
Completed 1046/2700
Completed 1047/2700
Completed 1048/2700
Completed 1049/2700
Completed 1050/2700
Completed 1051/2700
Completed 1052/2700
Completed 1053/2700
Completed 1054/2700
Completed 1055/2700

In [17]:
results = evaluate_dataset(
    all_predictions,
    all_gold_spans,
    overlap_threshold=0.3
)

print("========== FULL DATASET EVALUATION ==========")

print("Precision:", results["precision"])
print("Recall:   ", results["recall"])
print("F1 Score: ", results["f1"])

print()
print("True Positives: ", results["total_tp"])
print("False Positives:", results["total_fp"])
print("False Negatives:", results["total_fn"])

========== FULL DATASET EVALUATION ==========
Precision: 0.447
Recall:    0.434
F1 Score:  0.44

True Positives:  665
False Positives: 823
False Negatives: 868

In [18]:
for i in range(10):
    print(f"\n========== Example {i} ==========")
    print("LettuceDetect predictions:")
    print(all_predictions[i])

    print("RAGTruth gold spans:")
    print(all_gold_spans[i])

    print("Number predicted:", len(all_predictions[i]))
    print("Number gold:", len(all_gold_spans[i]))

========== Example 0 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 1 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 2 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 3 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 4 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[{'start': 0, 'end': 106, 'text': 'Three women, including Keonna Thomas of Philadelphia, were charged with attempting to join ISIS this week.', 'meta': 'EVIDENT CONFLICT:\nOriginal: Three women, including Keonna Thomas of Philadelphia, were charged with attempting to join ISIS this week.\nAIGC: It is Keonna Thomas who is charged of attempting to join ISIS. Meanwhile, the other two were arrested and accused of planning to build an explosive device for attacks in the United States.', 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}, {'start': 150, 'end': 178, 'text': 'was arrested before her trip', 'meta': "EVIDENT CONFLICT:\nOriginal:  It's not clear when or where she was arrested. \nAIGC:was arrested before her trip\n", 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}]
Number predicted: 0
Number gold: 2

========== Example 5 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[{'start': 110, 'end': 138, 'text': 'She was arrested on March 26', 'meta': "EVIDENT CONFLICT:\nOriginal:  It's not clear when or where she was arrested. \nAIGC: She was arrested on March 26", 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}]
Number predicted: 0
Number gold: 1

========== Example 6 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 7 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

========== Example 8 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[{'start': 61, 'end': 119, 'text': 'No Blue Bell Ice Cream Is Linked to Infections in Patients', 'meta': 'EVIDENT CONFLICT:\nOriginal:  Five people were infected and three died in the past year in Kansas from listeria\nAIGC: No Blue Bell Ice Cream Is Linked to Infections in Patients', 'label_type': 'Evident Conflict', 'implicit_true': False, 'due_to_null': False}]
Number predicted: 0
Number gold: 1

========== Example 9 ==========
LettuceDetect predictions:
[]
RAGTruth gold spans:
[]
Number predicted: 0
Number gold: 0

In [19]:
results_010 = evaluate_dataset(
    all_predictions,
    all_gold_spans,
    overlap_threshold=0.1
)

print("========== FULL DATASET EVALUATION (threshold=0.1) ==========")
print("Precision:", results_010["precision"])
print("Recall:   ", results_010["recall"])
print("F1 Score: ", results_010["f1"])
print()
print("True Positives: ", results_010["total_tp"])
print("False Positives:", results_010["total_fp"])
print("False Negatives:", results_010["total_fn"])

========== FULL DATASET EVALUATION (threshold=0.1) ==========
Precision: 0.504
Recall:    0.489
F1 Score:  0.497

True Positives:  750
False Positives: 738
False Negatives: 783

In [20]:
false_positives_010 = []
false_negatives_010 = []

for i in range(len(dataset["test"])):

    example = dataset["test"][i]

    preds = all_predictions[i]
    golds = all_gold_spans[i]

    matched, unmatched_preds, unmatched_golds = match_spans(
        preds,
        golds,
        overlap_threshold=0.1
    )

    for pred in unmatched_preds:
        false_positives_010.append({
            "index": i,
            "id": example["id"],
            "context": example["context"],
            "answer": example["output"],
            "predicted_text": pred["text"],
            "pred_start": pred["start"],
            "pred_end": pred["end"],
            "confidence": pred.get("confidence", None)
        })

    for gold in unmatched_golds:
        false_negatives_010.append({
            "index": i,
            "id": example["id"],
            "context": example["context"],
            "answer": example["output"],
            "gold_text": gold["text"],
            "gold_start": gold["start"],
            "gold_end": gold["end"],
            "label_type": gold.get("label_type", "")
        })

print("False Positives (threshold=0.1):", len(false_positives_010))
print("False Negatives (threshold=0.1):", len(false_negatives_010))

False Positives (threshold=0.1): 738
False Negatives (threshold=0.1): 783

In [21]:
import random

random.seed(42)

sample_fp_010 = random.sample(
    false_positives_010,
    min(50, len(false_positives_010))
)

print("New FP sample (threshold=0.1):", len(sample_fp_010))

New FP sample (threshold=0.1): 50

In [22]:
import pandas as pd

rows_010 = []

for x in sample_fp_010:
    rows_010.append({
        "example_id": x["id"],
        "context": x["context"],
        "answer": x["answer"],
        "problem_span": x["predicted_text"],
        "actually_hallucination": "",   # fill in YES / NO / UNSURE by hand
        "notes": ""
    })

review_df_010 = pd.DataFrame(rows_010)

review_df_010.to_csv("fp_review_threshold_010.csv", index=False)
print("Saved: fp_review_threshold_010.csv")

Saved: fp_review_threshold_010.csv

In [23]:
with open("false_negatives_010.json", "w") as f:
    json.dump(false_negatives_010, f)

print("Exported:", len(false_negatives_010), "false negatives")

Exported: 783 false negatives

In [24]:
import json
import random
import pandas as pd

# --------------------------------------------------
# 1. Load the false negatives exported from the notebook
# --------------------------------------------------

with open("false_negatives_010.json") as f:
    false_negatives_010 = json.load(f)

print("Loaded false negatives:", len(false_negatives_010))


# --------------------------------------------------
# 2. Sample 100 for manual review
# --------------------------------------------------

random.seed(42)

sample_fn_100 = random.sample(
    false_negatives_010,
    min(100, len(false_negatives_010))
)

print("FN sample size:", len(sample_fn_100))


# --------------------------------------------------
# 3. Build review sheet
# --------------------------------------------------

rows_fn = []

for x in sample_fn_100:
    rows_fn.append({
        "example_id": x["id"],
        "context": x["context"],
        "answer": x["answer"],
        "missed_span": x["gold_text"],
        "label_type": x["label_type"],
        "category": "",     # fill in by hand
        "notes": ""
    })

fn_review_df = pd.DataFrame(rows_fn)

fn_review_df.to_csv("100_fn_cases.csv", index=False)
print("Saved: 100_fn_cases.csv")

Loaded false negatives: 783
FN sample size: 100
Saved: 100_fn_cases.csv

In [31]:
import re
import ast

def extract_structured_data(context: str) -> dict:
    match = re.search(r"\{.*\}", context, flags=re.DOTALL)
    if not match:
        return {}
    raw = match.group(0)
    try:
        data = ast.literal_eval(raw)
        if isinstance(data, dict):
            return data
    except (ValueError, SyntaxError):
        pass
    return {}


ATTRIBUTE_KEYWORDS = {
    "WiFi": ["wifi", "wi-fi", "internet access"],
    "RestaurantsReservations": ["reservation"],
    "OutdoorSeating": ["outdoor seating", "outdoor dining", "patio seating"],
    "RestaurantsTakeOut": ["takeout", "take-out", "take out"],
    "RestaurantsGoodForGroups": ["good for groups", "suitable for groups", "great for groups"],
    "Music": ["live music", "music performance", "music venue"],
    "BusinessParking": ["parking"],
}

NEGATION_PATTERNS = re.compile(
    r"\b(no|not|without|does not offer|doesn't offer|unavailable|none available)\b",
    re.IGNORECASE
)

HEDGE_PATTERNS = re.compile(
    r"\b(does not mention|doesn't mention|no information|not specify|"
    r"not specified|unclear whether|not clear if|not indicate|"
    r"doesn't indicate|does not indicate|not provide information|"
    r"no data|not stated|unknown whether|no details|"
    r"not provide (specific )?details|does not offer|doesn't offer|"
    r"does not provide|doesn't provide|lacks information|"
    r"no mention|not mentioned|not available information)\b",
    re.IGNORECASE
)


def check_boolean_attributes(attributes: dict, answer: str) -> list:
    flags = []
    answer_lower = answer.lower()

    for field, keywords in ATTRIBUTE_KEYWORDS.items():
        source_value = attributes.get(field, "MISSING")

        for kw in keywords:
            idx = answer_lower.find(kw)
            if idx == -1:
                continue

            window_start = max(0, idx - 60)
            window_end = min(len(answer), idx + len(kw) + 60)
            snippet = answer[window_start:window_end]

            if HEDGE_PATTERNS.search(snippet):
                break

            if source_value is None or source_value == "MISSING":
                flags.append({
                    "field": field,
                    "issue": "attribute-invention",
                    "detail": f"Answer makes a claim about '{field}' "
                              f"({kw!r}) but source value is unknown/None.",
                    "snippet": snippet,
                })
            else:
                source_is_negative = source_value in (False, "no", "none", None)
                mentions_negation = bool(NEGATION_PATTERNS.search(snippet))

                if source_is_negative and not mentions_negation:
                    flags.append({
                        "field": field,
                        "issue": "attribute-contradiction",
                        "detail": f"Source says '{field}'={source_value!r} "
                                  f"(negative/false) but answer's mention "
                                  f"of {kw!r} doesn't read as a negation.",
                        "snippet": snippet,
                    })
                elif not source_is_negative and mentions_negation:
                    flags.append({
                        "field": field,
                        "issue": "attribute-contradiction",
                        "detail": f"Source says '{field}'={source_value!r} "
                                  f"(positive) but answer negates {kw!r}.",
                        "snippet": snippet,
                    })
            break

    return flags


def _to_12h(hour_str: str) -> str:
    try:
        h, m = hour_str.split(":")
        h, m = int(h), int(m)
    except ValueError:
        return hour_str
    period = "AM" if h < 12 else "PM"
    h12 = h % 12
    if h12 == 0:
        h12 = 12
    return f"{h12}:{m:02d} {period}"


TIME_PATTERN = re.compile(r"\b(\d{1,2})(?::(\d{2}))?\s*(AM|PM|am|pm)\b")


def check_hours(hours_dict: dict, answer: str) -> list:
    flags = []
    if not hours_dict:
        return flags

    valid_times = set()
    for day_range in hours_dict.values():
        if not day_range:
            continue
        for segment in str(day_range).split(","):
            segment = segment.strip()
            if "-" not in segment:
                continue
            open_t, close_t = segment.split("-", 1)
            valid_times.add(_to_12h(open_t.strip()))
            valid_times.add(_to_12h(close_t.strip()))

    if not valid_times:
        return flags

    for m in TIME_PATTERN.finditer(answer):
        hour, minute, period = m.groups()
        minute = minute or "00"
        stated = f"{int(hour)}:{minute} {period.upper()}"

        if stated not in valid_times:
            window_start = max(0, m.start() - 40)
            window_end = min(len(answer), m.end() + 40)
            flags.append({
                "field": "hours",
                "issue": "hours-mismatch",
                "detail": f"Answer states {stated!r}, doesn't match source hours.",
                "snippet": answer[window_start:window_end],
            })

    return flags


def check_attributes(context: str, answer: str) -> list:
    data = extract_structured_data(context)
    if not data:
        return []
    attributes = data.get("attributes", {}) or {}
    hours = data.get("hours", {}) or {}
    flags = []
    flags.extend(check_boolean_attributes(attributes, answer))
    flags.extend(check_hours(hours, answer))
    return flags


print("check_attributes() defined and ready to use.")

check_attributes() defined and ready to use.

In [32]:
invention_only_predictions = []

for i in range(len(dataset["test"])):
    example = dataset["test"][i]
    context = example["context"]
    answer = example["output"]

    flags = check_attributes(context, answer)

    example_preds = []
    for f in flags:
        if f["issue"] not in ("attribute-invention", "hours-mismatch"):
            continue
        pos = answer.find(f["snippet"])
        if pos == -1:
            continue
        example_preds.append({
            "start": pos,
            "end": pos + len(f["snippet"]),
            "text": f["snippet"],
            "confidence": None,
            "source": "rule"
        })

    invention_only_predictions.append(example_preds)

total_invention_flags = sum(len(p) for p in invention_only_predictions)
print("Invention+hours-only flags (with hedge fix):", total_invention_flags)

Invention+hours-only flags (with hedge fix): 258

In [33]:
hybrid_predictions_narrow = []

for lettuce_preds, rule_preds in zip(all_predictions, invention_only_predictions):
    hybrid_predictions_narrow.append(lettuce_preds + rule_preds)

results_hybrid_narrow = evaluate_dataset(
    hybrid_predictions_narrow,
    all_gold_spans,
    overlap_threshold=0.1
)

print("========== NARROW HYBRID (with hedge fix) ==========")
print("Precision:", results_hybrid_narrow["precision"])
print("Recall:   ", results_hybrid_narrow["recall"])
print("F1 Score: ", results_hybrid_narrow["f1"])
print()
print("True Positives: ", results_hybrid_narrow["total_tp"])
print("False Positives:", results_hybrid_narrow["total_fp"])
print("False Negatives:", results_hybrid_narrow["total_fn"])

print()
print("========== COMPARISON ==========")
print(f"{'Metric':<12}{'Baseline':<12}{'Narrow(before)':<16}{'Narrow(fixed)':<12}")
print(f"{'Precision':<12}{results_010['precision']:<12}{0.456:<16}{results_hybrid_narrow['precision']:<12}")
print(f"{'Recall':<12}{results_010['recall']:<12}{0.537:<16}{results_hybrid_narrow['recall']:<12}")
print(f"{'F1':<12}{results_010['f1']:<12}{0.493:<16}{results_hybrid_narrow['f1']:<12}")

========== NARROW HYBRID (with hedge fix) ==========
Precision: 0.465
Recall:    0.53
F1 Score:  0.495

True Positives:  812
False Positives: 934
False Negatives: 721

========== COMPARISON ==========
Metric      Baseline    Narrow(before)  Narrow(fixed)
Precision   0.504       0.456           0.465
Recall      0.489       0.537           0.53
F1          0.497       0.493           0.495

In [29]:
rule_fp_examples_v2 = []

for i in range(len(dataset["test"])):
    preds = invention_only_predictions[i]
    if not preds:
        continue
    golds = all_gold_spans[i]

    matched, unmatched_preds, _ = match_spans(preds, golds, overlap_threshold=0.1)

    for p in unmatched_preds:
        rule_fp_examples_v2.append({
            "index": i,
            "id": dataset["test"][i]["id"],
            "flagged_text": p["text"],
            "answer": dataset["test"][i]["output"],
        })

print("Total rule false positives (after hedge fix):", len(rule_fp_examples_v2))

import random
random.seed(7)  # different seed so we see a fresh batch this time
sample = random.sample(rule_fp_examples_v2, min(20, len(rule_fp_examples_v2)))

for s in sample:
    print(f"\n[{s['id']}] flagged: {s['flagged_text']!r}")

Total rule false positives (after hedge fix): 119

[7780] flagged: 'nformed.\n\nThe restaurant has attributes such as no business parking, no outdoor seating, and no WiFi. They do offer takeout and'

[7000] flagged: 'ta, the business does not offer BusinessParking, RestaurantsReservations, OutdoorSeating, WiFi, or RestaurantsTakeOut. However, it '

[8148] flagged: 'are no details on whether the business offers services like WiFi, outdoor seating, or is good for groups.'

[8670] flagged: ' not provide specific details on amenities such as business parking, reservations, outdoor seating, WiFi, takeout options, musi'

[6686] flagged: ' information about the business, including parking options, reservation policies, outdoor seating availability, WiFi accessibility,'

[6719] flagged: 'biance. Free Wi-Fi is available, and the restaurant accepts reservations and takeout orders. Overall, Mr. B Restaurant & Cafe is a '

[9936] flagged: 'oor seating only becomes available from 8:00 AM.'

[8560] flagged: 'pen Monday through Saturday from 6am to 6:30pm, with a break from 12pm to 1pm. They ha'

[6901] flagged: ' the helpfulness and accommodation of Kathy when making the reservation. Captain Mike shared interesting information about Santa Ba'

[7981] flagged: 'bout parking, reservations, outdoor seating, WiFi, takeout, good for groups, music, or ambience.'

[8665] flagged: 'ay-Friday happy hour that extends until 7pm, which is a rare find. Customers have t'

[6686] flagged: 'policies, outdoor seating availability, WiFi accessibility, takeout options, group accommodations, music selection, ambiance, a'

[11190] flagged: 'itable for group dining. However, it does not offer WiFi or live music. The ambiance is described as casual. The restaurant has a '

[8557] flagged: 'ut service, WiFi availability, or whether the restaurant is good for groups. However, it does mention that outdoor seating is available'

[7159] flagged: ', Tuesday and Sunday from 12:0 PM to 10:0 PM, Wednesday and Thursday from 1:0 PM to '

[6634] flagged: ' open seven days a week from 0:00 AM to 0:00 AM, with parking available on the street a'

[6776] flagged: 'm Monday through Sunday from 4:00 PM to 9:00 PM.\n\nThe restaurant has free Wi-Fi, outdoo'

[8472] flagged: 'by customers. Despite mixed reviews about the ambiance, the takeout food receives consistent praise. Your Place Thai Restaurant'

[8152] flagged: ' from 9am to 5pm, and they offer outdoor seating, wifi, and takeout options. However, they do not accept reservations or provid'

[6718] flagged: ' to 8pm. It offers free WiFi, outdoor seating, takeout, and reservations. The menu includes a variety of dishes such as shawarma, h'

In [ ]:
rule_predictions = []

for i in range(len(dataset["test"])):
    example = dataset["test"][i]
    context = example["context"]
    answer = example["output"]

    flags = check_attributes(context, answer)

    example_preds = []
    for f in flags:
        pos = answer.find(f["snippet"])
        if pos == -1:
            continue
        example_preds.append({
            "start": pos,
            "end": pos + len(f["snippet"]),
            "text": f["snippet"],
            "confidence": None,
            "source": "rule"
        })

    rule_predictions.append(example_preds)

total_rule_flags = sum(len(p) for p in rule_predictions)
print("Total rule-based flags across dataset:", total_rule_flags)

Total rule-based flags across dataset: 785

In [ ]:
hybrid_predictions = []

for lettuce_preds, rule_preds in zip(all_predictions, rule_predictions):
    hybrid_predictions.append(lettuce_preds + rule_preds)

print("Hybrid predictions built for", len(hybrid_predictions), "examples")

Hybrid predictions built for 2700 examples

In [ ]:
results_hybrid = evaluate_dataset(
    hybrid_predictions,
    all_gold_spans,
    overlap_threshold=0.1
)

print("========== HYBRID SYSTEM EVALUATION (threshold=0.1) ==========")
print("Precision:", results_hybrid["precision"])
print("Recall:   ", results_hybrid["recall"])
print("F1 Score: ", results_hybrid["f1"])
print()
print("True Positives: ", results_hybrid["total_tp"])
print("False Positives:", results_hybrid["total_fp"])
print("False Negatives:", results_hybrid["total_fn"])

========== HYBRID SYSTEM EVALUATION (threshold=0.1) ==========
Precision: 0.372
Recall:    0.552
F1 Score:  0.445

True Positives:  846
False Positives: 1427
False Negatives: 687

In [34]:
gap_fill_predictions = []

for lettuce_preds, rule_preds in zip(all_predictions, invention_only_predictions):
    if len(lettuce_preds) == 0:
        # LettuceDetect found nothing here — let the rule fill the gap
        gap_fill_predictions.append(lettuce_preds + rule_preds)
    else:
        # LettuceDetect already made predictions — trust it, don't add rule noise
        gap_fill_predictions.append(lettuce_preds)

results_gap_fill = evaluate_dataset(
    gap_fill_predictions,
    all_gold_spans,
    overlap_threshold=0.1
)

print("========== GAP-FILL HYBRID ==========")
print("Precision:", results_gap_fill["precision"])
print("Recall:   ", results_gap_fill["recall"])
print("F1 Score: ", results_gap_fill["f1"])
print()
print("True Positives: ", results_gap_fill["total_tp"])
print("False Positives:", results_gap_fill["total_fp"])
print("False Negatives:", results_gap_fill["total_fn"])

print()
print("========== FULL COMPARISON ==========")
print(f"{'Metric':<12}{'Baseline':<12}{'Narrow(fixed)':<16}{'Gap-fill':<12}")
print(f"{'Precision':<12}{results_010['precision']:<12}{results_hybrid_narrow['precision']:<16}{results_gap_fill['precision']:<12}")
print(f"{'Recall':<12}{results_010['recall']:<12}{results_hybrid_narrow['recall']:<16}{results_gap_fill['recall']:<12}")
print(f"{'F1':<12}{results_010['f1']:<12}{results_hybrid_narrow['f1']:<16}{results_gap_fill['f1']:<12}")

========== GAP-FILL HYBRID ==========
Precision: 0.495
Recall:    0.5
F1 Score:  0.498

True Positives:  767
False Positives: 782
False Negatives: 766

========== FULL COMPARISON ==========
Metric      Baseline    Narrow(fixed)   Gap-fill
Precision   0.504       0.465           0.495
Recall      0.489       0.53            0.5
F1          0.497       0.495           0.498

In [ ]:
# --------------------------------------------------
# Split rule flags: invention/hours only vs everything
# --------------------------------------------------

invention_only_predictions = []

for i in range(len(dataset["test"])):
    example = dataset["test"][i]
    context = example["context"]
    answer = example["output"]

    flags = check_attributes(context, answer)

    example_preds = []
    for f in flags:
        if f["issue"] not in ("attribute-invention", "hours-mismatch"):
            continue  # skip the coarse attribute-contradiction flags
        pos = answer.find(f["snippet"])
        if pos == -1:
            continue
        example_preds.append({
            "start": pos,
            "end": pos + len(f["snippet"]),
            "text": f["snippet"],
            "confidence": None,
            "source": "rule"
        })

    invention_only_predictions.append(example_preds)

total_invention_flags = sum(len(p) for p in invention_only_predictions)
print("Invention+hours-only flags:", total_invention_flags)
print("(compare to 785 total flags including contradiction check)")

Invention+hours-only flags: 317
(compare to 785 total flags including contradiction check)

In [ ]:
# --------------------------------------------------
# Build the narrower hybrid and re-evaluate
# --------------------------------------------------

hybrid_predictions_narrow = []

for lettuce_preds, rule_preds in zip(all_predictions, invention_only_predictions):
    hybrid_predictions_narrow.append(lettuce_preds + rule_preds)

results_hybrid_narrow = evaluate_dataset(
    hybrid_predictions_narrow,
    all_gold_spans,
    overlap_threshold=0.1
)

print("========== NARROW HYBRID (invention + hours only) ==========")
print("Precision:", results_hybrid_narrow["precision"])
print("Recall:   ", results_hybrid_narrow["recall"])
print("F1 Score: ", results_hybrid_narrow["f1"])
print()
print("True Positives: ", results_hybrid_narrow["total_tp"])
print("False Positives:", results_hybrid_narrow["total_fp"])
print("False Negatives:", results_hybrid_narrow["total_fn"])

print()
print("========== COMPARISON ==========")
print(f"{'Metric':<12}{'Baseline':<12}{'Full rule':<12}{'Narrow rule':<12}")
print(f"{'Precision':<12}{results_010['precision']:<12}{results_hybrid['precision']:<12}{results_hybrid_narrow['precision']:<12}")
print(f"{'Recall':<12}{results_010['recall']:<12}{results_hybrid['recall']:<12}{results_hybrid_narrow['recall']:<12}")
print(f"{'F1':<12}{results_010['f1']:<12}{results_hybrid['f1']:<12}{results_hybrid_narrow['f1']:<12}")

========== NARROW HYBRID (invention + hours only) ==========
Precision: 0.456
Recall:    0.537
F1 Score:  0.493

True Positives:  823
False Positives: 982
False Negatives: 710

========== COMPARISON ==========
Metric      Baseline    Full rule   Narrow rule
Precision   0.504       0.372       0.456
Recall      0.489       0.552       0.537
F1          0.497       0.445       0.493

In [ ]:
# --------------------------------------------------
# Sample some of the rule's flags that did NOT match
# any gold span, to see what's going wrong
# --------------------------------------------------

rule_fp_examples = []

for i in range(len(dataset["test"])):
    preds = invention_only_predictions[i]
    if not preds:
        continue
    golds = all_gold_spans[i]

    matched, unmatched_preds, _ = match_spans(preds, golds, overlap_threshold=0.1)

    for p in unmatched_preds:
        rule_fp_examples.append({
            "index": i,
            "id": dataset["test"][i]["id"],
            "flagged_text": p["text"],
            "answer": dataset["test"][i]["output"],
        })

print("Total rule false positives:", len(rule_fp_examples))

import random
random.seed(42)
sample = random.sample(rule_fp_examples, min(15, len(rule_fp_examples)))

for s in sample:
    print(f"\n[{s['id']}] flagged: {s['flagged_text']!r}")

Total rule false positives: 133

[7024] flagged: 'hours of operation are from 12:00 pm to 20:00 pm from Monday to Thursday, and from 11:00'

[6631] flagged: ' services. The data does not mention if reservations are accepted or if outdoor seating is '

[8557] flagged: 'staurant reservations, takeout service, WiFi availability, or whether the restaurant'

[8148] flagged: 'vices like WiFi, outdoor seating, or is good for groups.'

[7984] flagged: 'o 2pm every day, and offers takeout and outdoor seating. No reservations are available, but cus'

[7159] flagged: ' 10:0 PM, Wednesday and Thursday from 1:0 PM to 11:0 PM, and Friday from 12:0 PM to '

[7000] flagged: 'ta, the business does not offer BusinessParking, RestaurantsReservations, OutdoorSeatin'

[6998] flagged: 'r amenities such as WiFi, reservations, outdoor seating, or takeout. According to customer revi'

[9553] flagged: 'ion available about the availability of WiFi or takeout options.\n\nIn conclusion, Old'

[6634] flagged: 'business is open seven days a week from 0:00 AM to 0:00 AM, with parking available on t'

[6631] flagged: 'tion if reservations are accepted or if outdoor seating is available. \n\nThe overall rating for '

[6998] flagged: 'WiFi, reservations, outdoor seating, or takeout. According to customer reviews, Harbor '

[7981] flagged: 'ations, outdoor seating, WiFi, takeout, good for groups, music, or ambience.'

[7985] flagged: 'he portion sizes. The restaurant offers takeout and reservations, and is open seven day'

[10816] flagged: 'tured data, they offer takeout and have outdoor seating, but do not provide WiFi or accept rese'

In [ ]:
import pandas as pd

df = pd.read_csv("categorized_errors.csv")

baseless_cases = df[
    df["category"] == "Baseless/unsupported info"
].copy()

print("Baseless/unsupported cases found:", len(baseless_cases))

baseless_cases["sub_pattern"] = ""   # you'll fill this in by hand
baseless_cases["notes"] = ""

baseless_cases.to_csv("30_baseless_cases.csv", index=False)
print("Saved: 30_baseless_cases.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'categorized_errors.csv'

In [ ]:
print("Examples evaluated:", len(all_predictions))

print(
    "Examples where LettuceDetect predicted something:",
    sum(len(x) > 0 for x in all_predictions)
)

print(
    "Total LettuceDetect predicted spans:",
    sum(len(x) for x in all_predictions)
)

print(
    "Total RAGTruth gold spans:",
    sum(len(x) for x in all_gold_spans)
)

Examples evaluated: 2700
Examples where LettuceDetect predicted something: 709
Total LettuceDetect predicted spans: 1488
Total RAGTruth gold spans: 1533

In [ ]:
import re

def text_overlap_ratio(pred_text: str, gold_text: str) -> float:
    """Rough token-overlap check, independent of character offsets."""
    p_tokens = set(re.findall(r"\w+", pred_text.lower()))
    g_tokens = set(re.findall(r"\w+", gold_text.lower()))
    if not p_tokens or not g_tokens:
        return 0.0
    return len(p_tokens & g_tokens) / len(p_tokens | g_tokens)


def diagnose_offset_alignment(all_predictions, all_gold_spans, answers, n_show=8):
    """
    Finds cases where pred/gold spans clearly describe the same text
    (high token overlap) but score low/zero on char-offset IoU.
    If these are common, you likely have an offset-basis mismatch,
    not a genuine detection miss.
    """
    suspects = []

    for ex_idx, (preds, golds) in enumerate(zip(all_predictions, all_gold_spans)):
        for pred in preds:
            for gold in golds:
                char_iou = span_overlap(
                    (pred["start"], pred["end"]),
                    (gold["start"], gold["end"]),
                )
                txt_overlap = text_overlap_ratio(
                    pred.get("text", ""), gold.get("text", "")
                )

                # High text similarity but low/no char overlap = red flag
                if txt_overlap >= 0.5 and char_iou < 0.3:
                    suspects.append({
                        "example_idx": ex_idx,
                        "pred_text": pred.get("text", ""),
                        "pred_span": (pred["start"], pred["end"]),
                        "gold_text": gold.get("text", ""),
                        "gold_span": (gold["start"], gold["end"]),
                        "char_iou": round(char_iou, 3),
                        "text_overlap": round(txt_overlap, 3),
                    })

    print(f"Found {len(suspects)} likely offset-mismatch cases "
          f"(high text similarity, low char IoU)\n")

    for s in suspects[:n_show]:
        ex = s["example_idx"]
        answer_text = answers[ex]
        print("=" * 70)
        print(f"Example {ex}")
        print(f"  Pred text:  {s['pred_text']!r}")
        print(f"  Pred span:  {s['pred_span']}")
        print(f"  Gold text:  {s['gold_text']!r}")
        print(f"  Gold span:  {s['gold_span']}")
        print(f"  char IoU={s['char_iou']}  text_overlap={s['text_overlap']}")
        # Show what characters the answer text actually has at each span,
        # so you can see the shift directly
        p_s, p_e = s["pred_span"]
        g_s, g_e = s["gold_span"]
        print(f"  answer[pred_span] = {answer_text[p_s:p_e]!r}")
        print(f"  answer[gold_span] = {answer_text[g_s:g_e]!r}")
        print()

    return suspects


# You'll need the raw answer text per example to run the offset check below.
# Rebuild it alongside your existing loop, or re-derive it here:
answers = [dataset["test"][i]["output"] for i in range(len(all_predictions))]

suspects = diagnose_offset_alignment(all_predictions, all_gold_spans, answers)

Found 8 likely offset-mismatch cases (high text similarity, low char IoU)

======================================================================
Example 1204
  Pred text:  '100 reviews'
  Pred span:  (283, 294)
  Gold text:  '100'
  Gold span:  (283, 286)
  char IoU=0.273  text_overlap=0.5
  answer[pred_span] = '100 reviews'
  answer[gold_span] = '100'

======================================================================
Example 1240
  Pred text:  ' casual setting'
  Pred span:  (938, 953)
  Gold text:  'casual'
  Gold span:  (389, 395)
  char IoU=0.0  text_overlap=0.5
  answer[pred_span] = ' casual setting'
  answer[gold_span] = 'casual'

======================================================================
Example 1415
  Pred text:  ' has a casual, classy atmosphere'
  Pred span:  (836, 868)
  Gold text:  'has a cozy atmosphere'
  Gold span:  (1016, 1037)
  char IoU=0.0  text_overlap=0.5
  answer[pred_span] = ' has a casual, classy atmosphere'
  answer[gold_span] = 'has a cozy atmosphere'

======================================================================
Example 1517
  Pred text:  ' provides outdoor seating'
  Pred span:  (405, 430)
  Gold text:  'outdoor seating,'
  Gold span:  (1176, 1192)
  char IoU=0.0  text_overlap=0.667
  answer[pred_span] = ' provides outdoor seating'
  answer[gold_span] = 'outdoor seating,'

======================================================================
Example 1690
  Pred text:  ' trendy ambiance'
  Pred span:  (526, 542)
  Gold text:  'trendy'
  Gold span:  (1269, 1275)
  char IoU=0.0  text_overlap=0.5
  answer[pred_span] = ' trendy ambiance'
  answer[gold_span] = 'trendy'

======================================================================
Example 1732
  Pred text:  ' available'
  Pred span:  (404, 414)
  Gold text:  'WiFi available.'
  Gold span:  (452, 467)
  char IoU=0.0  text_overlap=0.5
  answer[pred_span] = ' available'
  answer[gold_span] = 'WiFi available.'

======================================================================
Example 1913
  Pred text:  ' Averages around 50-60 inches per year'
  Pred span:  (265, 303)
  Gold text:  'Averages around 20-30 inches per year'
  Gold span:  (402, 439)
  char IoU=0.0  text_overlap=0.556
  answer[pred_span] = ' Averages around 50-60 inches per year'
  answer[gold_span] = 'Averages around 20-30 inches per year'

======================================================================
Example 2133
  Pred text:  ' (mentioned in passage'
  Pred span:  (245, 267)
  Gold text:  '* Dizziness (mentioned in passage 5)'
  Gold span:  (126, 162)
  char IoU=0.0  text_overlap=0.6
  answer[pred_span] = ' (mentioned in passage'
  answer[gold_span] = '* Dizziness (mentioned in passage 5)'

In [ ]:
thresholds = [0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]

sweep_results = []
for t in thresholds:
    r = evaluate_dataset(all_predictions, all_gold_spans, overlap_threshold=t)
    sweep_results.append({"threshold": t, **r})
    print(f"threshold={t:>4}  P={r['precision']:.3f}  R={r['recall']:.3f}  "
          f"F1={r['f1']:.3f}  TP={r['total_tp']}  FP={r['total_fp']}  FN={r['total_fn']}")

threshold= 0.1  P=0.504  R=0.489  F1=0.497  TP=750  FP=738  FN=783
threshold=0.15  P=0.494  R=0.479  F1=0.487  TP=735  FP=753  FN=798
threshold= 0.2  P=0.480  R=0.466  F1=0.473  TP=714  FP=774  FN=819
threshold= 0.3  P=0.447  R=0.434  F1=0.440  TP=665  FP=823  FN=868
threshold= 0.4  P=0.407  R=0.395  F1=0.401  TP=606  FP=882  FN=927
threshold= 0.5  P=0.364  R=0.353  F1=0.358  TP=541  FP=947  FN=992
threshold= 0.6  P=0.321  R=0.311  F1=0.316  TP=477  FP=1011  FN=1056
threshold= 0.7  P=0.274  R=0.265  F1=0.269  TP=407  FP=1081  FN=1126

In [ ]:
false_positives = []
false_negatives = []

for i in range(len(dataset["test"])):

    example = dataset["test"][i]

    preds = all_predictions[i]
    golds = all_gold_spans[i]

    matched, unmatched_preds, unmatched_golds = match_spans(
        preds,
        golds,
        overlap_threshold=0.3
    )

    # False Positives
    for pred in unmatched_preds:
        false_positives.append({
            "index": i,
            "id": example["id"],
            "context": example["context"],
            "answer": example["output"],
            "predicted_text": pred["text"],
            "pred_start": pred["start"],
            "pred_end": pred["end"],
            "confidence": pred.get("confidence", None)
        })

    # False Negatives
    for gold in unmatched_golds:
        false_negatives.append({
            "index": i,
            "id": example["id"],
            "context": example["context"],
            "answer": example["output"],
            "gold_text": gold["text"],
            "gold_start": gold["start"],
            "gold_end": gold["end"],
            "label_type": gold.get("label_type", "")
        })

print("False Positives:", len(false_positives))
print("False Negatives:", len(false_negatives))

False Positives: 823
False Negatives: 868

In [ ]:
fp = false_positives[0]

print("========== FALSE POSITIVE ==========")

print("\nANSWER:")
print(fp["answer"])

print("\nLETTUCEDETECT WRONGLY FLAGGED:")
print(fp["predicted_text"])

print("\nCONFIDENCE:")
print(fp["confidence"])

========== FALSE POSITIVE ==========

ANSWER:
B.B. King, the legendary blues musician, was hospitalized for dehydration caused by his Type II diabetes. However, he has since been discharged and is now resting at home. The cause of his dehydration was attributed to his busy schedule and not drinking enough water. King is known for his hit songs such as "The Thrill Is Gone" and "There Must be a Better World Somewhere".

LETTUCEDETECT WRONGLY FLAGGED:
 he has since been discharged and is now resting

CONFIDENCE:
0.7028703689575195

In [ ]:
fn = false_negatives[0]

print("========== FALSE NEGATIVE ==========")

print("\nANSWER:")
print(fn["answer"])

print("\nRAGTRUTH SAYS THIS IS HALLUCINATED:")
print(fn["gold_text"])

print("\nHALLUCINATION TYPE:")
print(fn["label_type"])

========== FALSE NEGATIVE ==========

ANSWER:
Three women, including Keonna Thomas of Philadelphia, were charged with attempting to join ISIS this week. Thomas purchased a ticket to Barcelona but was arrested before her trip. Two other women, Noelle Velentzas and Asia Siddiqui, were arrested in New York for planning to build an explosive device. The FBI cited social media messages dating back to 2013 as evidence. This brings the total number of US citizens charged with supporting terrorism to over 30 in the past 18 months, with 18 of those cases involving ISIS.

RAGTRUTH SAYS THIS IS HALLUCINATED:
Three women, including Keonna Thomas of Philadelphia, were charged with attempting to join ISIS this week.

HALLUCINATION TYPE:
Evident Conflict

In [ ]:
fp = false_positives[0]

print("========== ORIGINAL SOURCE ==========")
print(fp["context"])

print("\n========== AI ANSWER ==========")
print(fp["answer"])

print("\n========== LETTUCEDETECT FLAGGED ==========")
print(fp["predicted_text"])

========== ORIGINAL SOURCE ==========
Blues legend B.B. King was hospitalized for dehydration, though the ailment didn't keep him out for long. King's dehydration was caused by his Type II diabetes, but he "is much better," his daughter, Claudette King, told the Los Angeles Times. The legendary guitarist and vocalist released a statement thanking those who have expressed their concerns. "I'm feeling much better and am leaving the hospital today," King said in a message Tuesday. Angela Moore, a publicist for Claudette King, said later in the day that he was back home resting and enjoying time with his grandchildren. "He was struggling before, and he is a trouper," Moore said. "He wasn't going to let his fans down." No more information on King's condition or where he was hospitalized was immediately available. B.B. is short for Blues Boy, part of the name he used as a Memphis disc jockey, the Beale Street Blues Boy. He was inducted into the Rock and Roll Hall of Fame in 1987, and has 30 Grammy nominations. King, 89, has used various models of Gibson guitars over the years, and named each one of them Lucille. In the 1980s, Gibson officially dropped the model number on the guitar he used last and most. It became a custom-made signature model named Lucille, manufactured exclusively for the "King of the Blues." Some of his hits include "The Thrill Is Gone," which won him his first Grammy in 1970, "There Must be a Better World Somewhere" and "When Love Comes to Town," a collaboration with U2. Last year, the bluesman suffered from dehydration and exhaustion after a show in Chicago, forcing him to cancel the remainder of his tour. CNN's Greg Botelho and Sonya Hamasaki contributed to this report.

output:

========== AI ANSWER ==========
B.B. King, the legendary blues musician, was hospitalized for dehydration caused by his Type II diabetes. However, he has since been discharged and is now resting at home. The cause of his dehydration was attributed to his busy schedule and not drinking enough water. King is known for his hit songs such as "The Thrill Is Gone" and "There Must be a Better World Somewhere".

========== LETTUCEDETECT FLAGGED ==========
 he has since been discharged and is now resting

In [ ]:
import random

random.seed(42)

sample_fp = random.sample(
    false_positives,
    min(50, len(false_positives))
)

sample_fn = random.sample(
    false_negatives,
    min(50, len(false_negatives))
)

print("FP sample:", len(sample_fp))
print("FN sample:", len(sample_fn))
print("Total errors to analyze:", len(sample_fp) + len(sample_fn))

FP sample: 50
FN sample: 50
Total errors to analyze: 100

In [ ]:
import pandas as pd

rows = []

for x in sample_fp:
    rows.append({
        "error_type": "FP",
        "example_id": x["id"],
        "context": x["context"],
        "answer": x["answer"],
        "problem_span": x["predicted_text"],
        "ragtruth_type": "",
        "reason": ""
    })

for x in sample_fn:
    rows.append({
        "error_type": "FN",
        "example_id": x["id"],
        "context": x["context"],
        "answer": x["answer"],
        "problem_span": x["gold_text"],
        "ragtruth_type": x["label_type"],
        "reason": ""
    })

error_df = pd.DataFrame(rows)

error_df.head()

,error_type,example_id,context,answer,problem_span,ragtruth_type,reason
0,FP,13532,One difference between the FEHA (the Fair Empl...,"Based on the given passages, we can see that t...",twenty or more employees,,
1,FP,6277,"\n{'name': 'Mala Town', 'address': '6555 Parda...",Mala Town is a local Chinese restaurant locate...,to,,
2,FP,1112,An American citizen was wounded by gunfire Thu...,An American woman working at a medical school ...,The attack occurred despite a recent surge in...,,
3,FP,16419,Page 1 of 2 Compliments of: Bob Bartelme Backw...,"Based on the provided passages, here is how yo...",truncated,,
4,FP,7231,"\n{'name': 'Eastside Deli', 'address': '10068 ...",Eastside Deli is a local business located at 1...,7:00 AM to 8:00 PM on weekends,,

In [ ]:
error_df.to_csv(
    "lettucedetect_error_analysis_100.csv",
    index=False
)

print("Saved!")

Saved!

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
error_df.to_csv(
    "/content/drive/MyDrive/lettucedetect_error_analysis_100.csv",
    index=False
)

print("Saved to Google Drive!")

Saved to Google Drive!

In [ ]:
import os

path = "/content/drive/MyDrive/lettucedetect_error_analysis_100.csv"

print("File exists:", os.path.exists(path))

File exists: True

In [ ]:
!pip install -q anthropic

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 43.0 MB/s eta 0:00:00

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/categorized_errors.csv"

df = pd.read_csv(file_path)

print("CSV loaded successfully!")
print("Rows:", len(df))
print("Columns:", df.columns.tolist())

df.head()

CSV loaded successfully!
Rows: 100
Columns: ['error_type', 'example_id', 'context', 'answer', 'problem_span', 'ragtruth_type', 'reason', 'category']

,error_type,example_id,context,answer,problem_span,ragtruth_type,reason,category
0,FP,13532,One difference between the FEHA (the Fair Empl...,"Based on the given passages, we can see that t...",twenty or more employees,NaN,NaN,Wrong occurrence / partial match
1,FP,6277,"\n{'name': 'Mala Town', 'address': '6555 Parda...",Mala Town is a local Chinese restaurant locate...,to,NaN,NaN,Boundary/tokenization artifact
2,FP,1112,An American citizen was wounded by gunfire Thu...,An American woman working at a medical school ...,The attack occurred despite a recent surge in...,NaN,NaN,Unsupported/fabricated (not annotated by gold)
3,FP,16419,Page 1 of 2 Compliments of: Bob Bartelme Backw...,"Based on the provided passages, here is how yo...",truncated,NaN,NaN,False alarm on supported content
4,FP,7231,"\n{'name': 'Eastside Deli', 'address': '10068 ...",Eastside Deli is a local business located at 1...,7:00 AM to 8:00 PM on weekends,NaN,NaN,Numbers/values mismatch

In [ ]:
for i in range(len(all_predictions)):
    answer = dataset["test"][i]["output"]
    for pred in all_predictions[i]:
        if pred["end"] > len(answer):
            print(f"Example {i} (id={dataset['test'][i]['id']}): "
                  f"pred end={pred['end']} exceeds len(answer)={len(answer)}")
            print(f"  pred text: {pred['text']!r}")
            print(f"  answer[pred['start']:pred['end']]: "
                  f"{answer[pred['start']:pred['end']]!r}")
            print()